sonar.projectKey=Ashutosh8007_banking-devsecops-project
sonar.organization=ashutosh8007
sonar.sources=Backend,Frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.tests=Backend/__tests__
